# Active Service (Production Traffic - Switches Between Blue/Green)
apiVersion: v1
kind: Service
metadata:
  name: bankapp-active-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  selector:
    app: bankapp
    version: blue  # This will be switched to 'green' during dep